import { SuggestedOption } from '@/components/SuggestedOptions/types';

export const defaultOptions: SuggestedOption[] = [
  {
    name: 'languageOptions',
    title: 'Languages to learn',
    description: 'Pick across most commonly used languages…',
    icon: 'Translate',
    options: [
      'English',
      'Mandarin Chinese',
      'Hindi',
      'Spanish',
      'French',
      'Standard Arabic',
      'Bengali',
      'Russian',
      'Portuguese',
      'Indonesian',
    ],
  },
  {
    name: 'skillsToLearnOptions',
    title: 'Skills to acquire',
    description:
      "Want to learn a new skill but don't know which one is best for you?",
    icon: 'DownhillSkiing',
    options: [
      'App Development (Programming)',
      'Copywriting',
      'UX and UI Design',
      'Video Game Development',
      'Digital Marketing & SEO',
      'Data Science',
      'Social Media Marketing & Management',
      'Product Design',
      'Video Editing',
      'eCommerce',
      'Business Analytics',
    ],
  },
  {
    name: 'freeTimeOptions',
    title: 'Free time options',
    description:
      'If you wonder how to spend your next hour or more, pick this one!',
    icon: 'BeachAccess',
    options: [
      'Reading',
      'Journaling/Writing',
      'Writing Poetry',
      'Performing Slam Poetry',
      'Sewing',
      'Walking',
      'Gardening',
      'Bird-Watching',
      'Painting',
      'Drawing',
      'Cooking',
      'Genealogy',
      'Become an Expert',
      'Jewelry-Making',
      'Guitar',
      'Card Tricks',
      'Play Cards',
      'Star-Gazing',
      'Fishing',
      'Photography',
      'Chess',
      'Whittling',
      'Puzzles',
      'Coding',
      'Dancing',
      'Scrapbooking',
      'Pinterest',
      'Raise Chickens',
      'Homesteading',
      'Papier Mache',
      'Origami',
      'Whistling',
      'Singing',
      'Make Recycled Art',
      'Blogging',
    ],
  },
];
